### ISSUE TITLE
FailedObjects There are too many failures, and the data in the target bucket and the source bucket are inconsistent.

### ISSUE THREAD

**Issue by coder-xsj** [awslabs/data-transfer-hub#127]
**Describe the bug**
The running plan lasted for 3 months and transferred 140 GB of data. There were too many FailedObjects failures and the data in the target bucket was inconsistent with the source bucket.

**Screenshots**
![TransferredFailedObjects](https://s2.loli.net/2023/10/21/Ra4VJ9IvmPSsY3f.png)

![image-20231021001348684](https://s2.loli.net/2023/10/21/pjn4xCBRyK3Xo9f.png)

 Version: v2.4.0
 Region (source): us-east-1
 Region (destination): cn-northwest-1

**Comment by YikaiHu** [comment]
Hi @coder-xsj ,
Could you please provide the log of Worker EC2?

**3. How to find detailed transfer log?**</br>

- **For Portal users**

    Go to **Tasks** list page, and click the **Task ID**. You can see the dashboard and logs under the **Monitoring** section.
    
    Data Transfer Hub has embedded Dashboard and log groups on the Portal, so you do not need to navigate to AWS CloudWatch console to view the logs.   

- **For Plugin (Pure Backend) users**

    When deploying the stack, you will be asked to enter the stack name (`DTHS3Stack` by default), and most resources will be created with the name prefix as the stack name. For example, the format of the queue name is `<StackName>-S3TransferQueue-<random suffix>`. This plugin will create two main log groups.

    - If there is no data transfer, you need to check whether there is a problem in the Finder task log. The following is the log group for scheduling Finder tasks. For more information, refer to the [Troubleshooting](../troubleshooting) section.
        
        `<StackName>-CommonS3RepWorkerLogGroup<random suffix>`

    - The following are the log groups of all EC2 instances, and you can find detailed transfer logs.

        `<StackName>-EC2WorkerStackS3RepWorkerLogGroup<random suffix>`

**Comment by YikaiHu** [comment]
Typically, this issue arises due to network throttling during prolonged periods of low bandwidth transmission. To circumvent this, we recommend using a script to periodically terminate the Worker EC2 instances. This action allows the Auto Scaling Group (ASG) to launch new instances with fresh IP addresses, which can help bypass the network throttling.

DTH runs default comparison tasks hourly, ensuring data consistency between the two sides. Therefore, you can rest assured about the final data consistency.

I am going to close this issue for now. If you encounter this problem again, please feel free to reopen this issue or create a new one.
