### ISSUE TITLE
Nodejs 10 being deprecated in AWS Lambda

### ISSUE THREAD

**Issue by tomclukies** [awslabs/data-transfer-hub#38]
DRH creates s3 replication Lambdas with node version 10. 

"AWS is ending support for Node.js 10 in AWS Lambda on July 30, 2021. This follows the Node.js language governing body declaring Node.js 10 end of life as of April 30, 2021."

Is there any workaround for this other than upgrading existing lambdas in place to a higher version? It seems there is no way to change which version is used with newly created S3 DRH tasks and associated lambdas.

**Comment by daixba** [comment]
We are currently working on the update for this, the new version will be released soon.  Before you, you can try directly using the S3 plugin. Below is the repo, it uses EC2 (graviton2) rather than lambda to do the data transfer and it performs better and costs less.

https://github.com/awslabs/amazon-s3-data-replication-hub-plugin

**Comment by tomclukies** [comment]
We use DRH for ECR as well. Looking forward to the update! :) Thanks!

**Comment by YikaiHu** [comment]
Hi @tomclukies , in Data Transfer Hub [v2.0.0](https://github.com/awslabs/data-transfer-hub), we updated the lambda to Node.js 14. 

And in this version, the S3 plugin launched by the UI will use EC2 (graviton2) by default.
